source 'https://github.com/CocoaPods/Specs.git'

platform :ios, '15.5'

project '/Users/jantonioencisos/Documents/iOS/Maps/Maps.xcodeproj'

target 'Maps' do
  pod 'GoogleMaps'
  pod 'Google-Maps-iOS-Utils'
  pod 'GooglePlaces'
  
post_install do |installer|
  installer.pods_project.targets.each do |target|
      target.build_configurations.each do |config|
        config.build_settings['ONLY_ACTIVE_ARCH'] = 'YES'
      end
  end
end
  
end
